# Generated by Django 6.0.5 on 2026-05-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_lesson_section_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='node_type',
            field=models.CharField(choices=[('introduction', 'Introduction'), ('application', 'Application'), ('competition', 'Competition'), ('test', 'Test')], default='introduction', max_length=20),
        ),
    ]
