# Generated by Django 6.0.5 on 2026-05-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_section_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('instruction', models.TextField()),
                ('hint', models.TextField(blank=True, default='')),
                ('starter_code', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('check_regex', models.CharField(blank=True, default='', max_length=500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('instruction', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('check_regex', models.CharField(blank=True, default='', max_length=500)),
                ('points', models.IntegerField(default=25)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='user.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
