# Generated by Django 6.0.5 on 2026-05-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_task_testquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('code', models.TextField(blank=True, default='')),
                ('highlighted_lines', models.CharField(blank=True, default='', help_text="Comma-separated line numbers to highlight e.g. '1,3,5'", max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='user.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
