# Generated by Django 6.0.5 on 2026-05-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level_required',
            field=models.IntegerField(default=1),
        ),
    ]
