# Generated by Django 6.0.5 on 2026-05-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_lesson_level_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='competition_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='speed_runs',
            field=models.IntegerField(default=0),
        ),
    ]
