# Generated by Django 6.0.5 on 2026-05-29 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_studentprofile_competition_wins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-scroll', max_length=50)),
                ('color', models.CharField(default='#7c3aed', max_length=20)),
                ('xp_reward', models.IntegerField(default=50)),
                ('age_group', models.CharField(choices=[('child', 'Child'), ('teen', 'Teen'), ('adult', 'Adult')], default='child', max_length=10)),
                ('node_type', models.CharField(blank=True, choices=[('introduction', 'Introduction'), ('application', 'Application'), ('competition', 'Competition'), ('test', 'Test')], default='', max_length=20)),
                ('target_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_ai', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'quest')},
            },
        ),
    ]
