# Generated by Django 6.0.5 on 2026-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_quest_userquest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=False, max_length=254, null=False, unique=True),
        ),
    ]
