# Generated by Django 6.0.5 on 2026-06-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_testquestion_user_testattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code_template',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('free_code', 'Free Code'), ('fill_blank', 'Fill in the Blank'), ('bug_fix', 'Bug Fix')], default='free_code', max_length=20),
        ),
    ]
