# Generated by Django 6.0.5 on 2026-06-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_task_code_template_task_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='topic_covered',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
