# Generated by Django 6.0.5 on 2026-06-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_task_topic_covered'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='compete_battles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='compete_wins',
            field=models.IntegerField(default=0),
        ),
    ]
