# Generated by Django 6.0.5 on 2026-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_section_age_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='age_group',
        ),
        migrations.AddField(
            model_name='slide',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
